version: "3.7"

services:
  caddy:
    build: .
    container_name: caddy
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile
      - CADDY_DOCKER_MODE=swarm=false
      - CADDY_DOCKER_CADDYFILE=hybrid
    entrypoint: ["/bin/sh", "-c"]
    command: |
      echo '(import-docker-proxy)

      evoapi.qbabit.com {
        reverse_proxy /socket.io/* evolution_api_v2:8080 {
          flush_interval -1
        }

        reverse_proxy evolution_api_v2:8080

        encode gzip
      }' > /etc/caddy/Caddyfile && caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    networks:
      - caddy
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy:
    external: true
